# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: omni-coveragereporter-python

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: .
        key: ${{ runner.os }}-omni
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Local
      run: make install-local
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip &&
        pip install omni-coveragereporter==0.0.3 &&
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi &&
        pip3 install coverage &&
        pip3 install pytest &&
        pip3 install GitPython &&
        pip3 install requests &&
        sed -i 's+${test}+'$(pwd)'/points+g' coverage.out &&
        sed -i 's+${test}+'$(pwd)'/src+g' clover.xml &&
        sed -i 's+${test}+'$(pwd)'+g' coverage-pc.out &&
        sed -i 's+${test}+'$(pwd)'+g' coverage-tc.out &&
        mkdir tmp
    - name: Generate Reports
      run: coverage run --source=omni-coveragereporter-python -m pytest -v && coverage json
    - name: Move reports to tmp - Test Single File Upload
      run: mv *.out tmp
    - name: Send No Python Report (Test without config)
      run: python3 omni-coveragereporter-python/src/omni_coveragereporter/omni_coveragereporter_python.py
    - name: Send single Python Report
      run: python3 omni-coveragereporter-python/src/omni_coveragereporter/omni_coveragereporter_python.py
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Move tmp to report - Test Multiple File Upload
      run: mv tmp/*.out .
    - name: Sends multiple Reports (Go, Python and PHP)
      run: python3 omni-coveragereporter-python/src/omni_coveragereporter/omni_coveragereporter_python.py
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}